Repository Hicoding-Groupware/hicoding-front, pull requests merged in 2023-12, with the labels that each got.

#14 Feat/#5/my lecture
  src/App.js
  src/apis/CourseAPICalls.js
  src/apis/MyCourseAPICalls.js
  src/components/modal/LectureDetailInfoModal.js
  src/components/modal/MyLectureDetailInfoModal.js
  src/modules/MyCourseModule.js
  src/pages/course/CourseList.js
  src/pages/course/InProgress.js
Labels: 🤍 기능개발

#16 git ignore에 .idea추가
  .gitignore
  src/App.js
  src/components/common/DetailNavBar.js
Labels: 🤍 기능개발, 💖 버그해결

#18 Feat/#5/my lecture
  .idea/misc.xml
  src/App.js
  src/apis/Api.js
  src/apis/MyCourseAPICalls.js
  src/components/course/lists/InProgressList.js
  src/course.css
  src/modules/MyCourseModule.js
  src/modules/index.js
  src/pages/course/CourseMain.js
  src/pages/course/MyCourseMain.js
Labels: 🤍 기능개발

#31 feat/#6/원생조회페이지완성
  package-lock.json
  package.json
  src/App.js
  src/Student.css
  src/apis/StudentAPICalls.js
  src/modules/StudentModule.js
  src/pages/student/StudentRegist.js
Labels: 🤍 기능개발

#37 Feature/#28 member update
  src/App.js
  src/apis/LoginAPICalls.js
  src/components/common/DetailNavBar.js
  src/components/common/ManagerDetailNavBar.js
  src/components/common/ManagerNavbar.js
  src/components/common/Navbar.js
  src/components/form/LoginForm.js
  src/components/modal/FirstLoginModal.js
  src/components/router/ProtectedRoute.js
  src/layouts/Layout.js
  src/mainCss/login.css
  src/mainCss/navbar.css
  src/modules/LoginModule.js
  src/utils/TokenUtils.js
Labels: 🤍 기능개발

#40 Feat/#19/my lecture
  .idea/workspace.xml
  package.json
  src/App.js
  src/apis/Api.js
  src/apis/MyCourseAPICalls.js
  src/components/common/DetailNavBar.js
  src/components/common/MyCourseSidebar.js
  src/components/course/lists/DailyAttendance.js
  src/components/course/lists/InProgressList.js
  src/components/course/lists/LastCourseList.js
  src/components/course/lists/ScheduledCourseList.js
  src/components/items/MyCourseListItem.js
  src/components/modal/MyLectureDetailInfo.js
  src/components/modal/MyLectureDetailInfoModal.js
  src/course.css
  src/fonts/Pretendard-Black.ttf
  src/fonts/Pretendard-Bold.ttf
  src/fonts/Pretendard-Light.ttf
  src/fonts/Pretendard-Medium.ttf
  src/fonts/Pretendard-Regular.ttf
  src/fonts/Pretendard-SemiBold.ttf
  src/modules/MyCourseModule.js
  src/pages/course/MyCourseMain.js
Labels: 🤍 기능개발

#43 2023-12-07 #1 네비바 구현
  src/components/common/ManagerDetailNavBar.js
  src/mainCss/navbar.css
Labels: ❤️릭팩도링

#44 Feat/#6/studentsearch
  src/Student.css
  src/apis/StudentAPICalls.js
  src/components/student/items/CourseTable.js
  src/components/student/items/StudentTable.js
  src/components/student/pagingBar/ModalPagingBar.js
  src/modules/StudentModule.js
  src/pages/student/Student.js
  src/pages/student/StudentModify.js
  src/pages/student/StudentRegist.js
Labels: 🤍 기능개발

#53 2023-12-15 #1 메인페이지 구현
  package-lock.json
  package.json
  public/img/nothing-img.png
  src/App.js
  src/apis/MessageAPICalls.js
  src/apis/MyCourseAPICalls.js
  src/components/common/DetailNavBar.js
  src/components/common/Navbar.js
  src/components/form/LoginForm.js
  src/components/items/MyCourseListItem.js
  src/components/modal/FirstLoginModal.js
  src/layouts/MainLayout.js
  src/layouts/MyPageLayout.js
  src/mainCss/main.css
  src/mainCss/navbar.css
  src/modules/MessageModule.js
  src/modules/index.js
  src/pages/main/Main.js
  src/pages/main/ManagerMain.js
  src/pages/main/mainCalender/MainCalender.js
  src/pages/main/mainCalender/MainManagerCalender.js
  src/pages/main/mainCourse/MainMyCourseListItem.js
  src/pages/main/mainMessage/MainMessage.js
  src/pages/main/paging/MMpagingBar.js
  src/pages/main/paging/MpagingBar.js
Labels: 🤍 기능개발

#54 2023-12-15 #1 메인페이지 조금더 수정
  src/pages/member/Login.js
Labels: ❤️릭팩도링

#55 2023-12-15 #1 로그인 페이지 조금 수정
  public/img/background.png
  public/img/backround.png
  public/img/camera.png
  public/img/logo2.png
  public/img/noUser.png
  src/App.js
  src/Login.js
  src/components/modal/ImageModify.js
  src/components/modal/ImageUpload.js
  src/mainCss/login.css
  src/mainCss/main.css
  src/pages/member/Profile.js
Labels: ❤️릭팩도링

#56 Feat/#41/daily attendance
  src/App.js
  src/apis/Api.js
  src/apis/AttendanceAPICalls.js
  src/apis/MyCourseAPICalls.js
  src/components/course/items/MyCourseListItem.js
  src/components/course/items/MyCourseStudentListItem.js
  src/components/course/lists/DailyAttendance.js
  src/components/course/lists/DailyAttendanceList.js
  src/components/course/lists/InProgressList.js
  src/components/course/lists/LastCourseList.js
  src/components/course/lists/ScheduledCourseList.js
  src/components/course/lists/inseon.js
  src/course.css
  src/modules/AttendanceModule.js
  src/modules/MyCourseModule.js
  src/modules/index.js
Labels: 🤍 기능개발

#62 2023-12-18 #1 login
  src/Student.css
  src/components/form/LoginForm.js
  src/components/modal/FirstLoginModal.js
  src/course.css
  src/mainCss/login.css
  src/pages/member/Profile.js
  src/pages/student/StudentRegist.js
  src/utils/Validation.js
Labels: ❤️릭팩도링

#63 Feat/#60/message manage
  src/Message.css
  src/apis/MessageAPICalls.js
  src/components/message/items/MessageReceive.js
  src/components/message/items/MessageSend.js
  src/components/student/items/CourseTable.js
  src/pages/message/Message.js
Labels: 🤍 기능개발

#64 Feat/89/course
  src/App.js
  src/apis/CourseAPICalls.js
  src/apis/LectureAPICalls.js
  src/components/Schedule/ClassroomCalendar.js
  src/components/course/items/CourseItem.js
  src/components/lecture/lists/LectureList.js
  src/components/lecture/modal/LectureUpdateModal.js
  src/modules/CourseModule.js
  src/modules/LectureModule.js
  src/pages/course/CourseModify.js
  src/pages/course/CourseRegist.js
  src/pages/lecture/LectureMain.js
  src/pages/schedule/AcademySchedule.js
  src/pages/schedule/ClassroomSchedule.js
Labels: ❤️릭팩도링, 🤍 기능개발

#66 Feat/#57/month attendance
  .idea/workspace.xml
  src/App.js
  src/Student.css
  src/apis/AttendanceAPICalls.js
  src/apis/CourseAPICalls.js
  src/apis/MemberAPICalls.js
  src/components/course/items/MyCourseStudentListItem.js
  src/components/course/items/MyCourseStudentListMonthItem.js
  src/components/course/lists/DailyAttendanceList.js
  src/components/course/lists/MonthAttendanceList.js
  src/components/course/lists/inseon.js
  src/course.css
  src/modules/AttendanceModule.js
  src/modules/MemberModule.js
  src/modules/index.js
Labels: 🤍 기능개발

#67 feat/#6/메세지기능구현완료
  src/apis/MessageAPICalls.js
  src/modules/MessageModule.js
  src/pages/message/Message.js
Labels: 🤍 기능개발

#68 feat/#6/메세지기능구현중
  src/components/common/DetailNavBar.js
Labels: 🤍 기능개발

#69 Feature/#1 main page
  public/img/play.png
  public/img/stop.png
  src/apis/Api.js
  src/apis/CourseAPICalls.js
  src/apis/LoginAPICalls.js
  src/apis/MessageAPICalls.js
  src/components/common/DetailNavBar.js
  src/components/form/LoginForm.js
  src/components/modal/FirstLoginModal.js
  src/components/modal/PasswordUpdateModal.js
  src/mainCss/main.css
  src/modules/LoginModule.js
  src/modules/MyCourseModule.js
  src/pages/main/Main.js
  src/pages/main/ManagerMain.js
  src/pages/main/mainCalender/MainManagerExpectedCalender.js
  src/pages/main/mainCalender/MainManagerProceedingCalender.js
  src/pages/main/mainCourse/MainCourseExpected.js
  src/pages/main/mainCourse/MainCourseProceeding.js
  src/pages/main/mainMessage/MainMessage.js
  src/pages/main/mainMyCourse/MainMyCourseListItem.js
  src/pages/main/paging/MainCourseProceedingPaging.js
  src/pages/member/Profile.js
Labels: ❤️릭팩도링

#70 feat/#60/메세지기능구현중
  src/components/course/items/MyCourseStudentListMonthItem.js
  src/pages/member/Profile.js
  src/pages/student/StudentModify.js
  src/pages/student/StudentRegist.js
Labels: 💖 버그해결

#71 Feat/#57/month attendance
  src/components/common/MyPagingBar.js
  src/components/course/items/MyCourseListItem.js
  src/components/course/items/MyCourseStudentListItem.js
  src/components/course/items/MyCourseStudentListMonthItem.js
  src/components/course/lists/InProgressList.js
  src/components/course/lists/LastCourseList.js
  src/components/course/lists/ScheduledCourseList.js
  src/course.css
Labels: 🤍 기능개발

#73 feat/#60/메세지기능구현중
  src/pages/student/StudentRegist.js
Labels: 💖 버그해결

#74 Feat/#57/month attendance
  src/components/course/items/MyCourseListItem.js
  src/components/course/items/MyCourseStudentListItem.js
  src/components/course/lists/InProgressList.js
  src/components/course/lists/LastCourseList.js
  src/components/course/lists/ScheduledCourseList.js
Labels: 💖 버그해결

#75 Feat/#57/month attendance
  src/components/course/items/MyCourseListItem.js
  src/components/course/items/MyCourseStudentListMonthItem.js
  src/components/modal/MyLectureDetailInfo.js
  src/course.css
Labels: 🤍 기능개발

#78 feat/#60/메세지기능구현중
  src/components/student/list/StudentList.js
  src/pages/member/Profile.js
  src/pages/message/Message.js
Labels: 💖 버그해결

#79 feat/#60/메세지기능구현중
  src/pages/message/Message.js
Labels: 💖 버그해결

#80 Feat/#57/month attendance
  src/components/course/items/MyCourseStudentListMonthItem.js
  src/components/course/lists/DailyAttendanceList.js
  src/course.css
Labels: 🤍 기능개발

#81 Feat/#57/month attendance
  src/components/course/items/MyCourseListItem.js
  src/components/course/items/MyCourseStudentListItem.js
  src/components/course/items/MyCourseStudentListMonthItem.js
  src/course.css
Labels: 💖 버그해결

#82 Feature/#1 main page
  src/components/common/DetailNavBar.js
  src/components/modal/FirstLoginModal.js
  src/components/modal/PasswordUpdateModal.js
  src/mainCss/main.css
  src/pages/main/Main.js
  src/pages/main/ManagerMain.js
  src/pages/main/mainBoard/MainBoard.js
  src/pages/main/mainCourse/MainCourseExpected.js
  src/pages/main/mainCourse/MainCourseProceeding.js
  src/pages/member/Profile.js
Labels: ❤️릭팩도링

#83 feat/#60/수강이력
  src/components/student/items/StudentTable.js
Labels: ❤️릭팩도링

#84 feat/#60/메세지기능리펙토링
  src/pages/message/Message.js
Labels: ❤️릭팩도링
